version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rjsmin
    versions:
    - "> 1.0.12, < 2"
  - dependency-name: rjsmin
    versions:
    - ">= 1.1.a, < 1.2"
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: pycodestyle
    versions:
    - 2.6.0
